### ISSUE TITLE
Fluentbit doesnt have access to mounted logs

### ISSUE THREAD

**Issue by ahvahsky2008** [bitnami/bitnami-docker-fluent-bit#5]
### Name and Version

bitnami/fluent-bit:1.9.3

### What steps will reproduce the bug?

I think docker-compose doesnt have access to mounted file. If i run ```fluent.exe -c index_formation.conf``` - all works perfect. But in docker is doesnt work

```
[2022/05/26 09:14:57] [ info] [cmetrics] version=0.3.0
[2022/05/26 09:14:57] [ info] [sp] stream processor started
[2022/05/26 09:14:57] [ info] [output:http:http.0] worker #0 started
[2022/05/26 09:14:57] [ info] [output:http:http.0] worker #1 started
[2022/05/26 09:14:57] [ info] [input:tail:tail.0] inotify_fs_add(): inode=10977524092265854 watch_fd=1 name=/opt/bitnami/fluent-bit/log/index.log
```

```
  fluent-bit:
    image: bitnami/fluent-bit:latest
    user: 1000:1000
    volumes:
      - ./fluent-bit-conf/index_formation.conf:/opt/bitnami/fluent-bit/conf/fluent-bit.conf
      - C:\Users\Admin\projects\index_formation\logs:/opt/bitnami/fluent-bit/log
  ```

```
[INPUT]
    name                  tail
    path                  /opt/bitnami/fluent-bit/log/*.log
    Path_Key              filename
    Mem_Buf_Limit         10MB
    Buffer_Chunk_Size     8k
    Buffer_Max_Size       32k
    Refresh_Interval      5

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      python

[OUTPUT]
    Name  http
    Match *
    Host  host.docker.internal
    Port  8000
    URI   /api/v1/
    header content-type application/json
    format json
	Retry_Limit     			15
	net.connect_timeout			20
	net.keepalive               on
    net.dns.mode                TCP
    net.connect_timeout         5```


### What is the expected behavior?

_No response_

### What do you see instead?

why it not works from docker?

### Additional information

_No response_
